'use strict';
let administration = require('../page-objects/administration');
let pupilLogin = require('../page-objects/pupilLogin');
let registration = require('../page-objects/registration');
let loginData = require('../shared-objects/loginData');
let performLogin = require('../page-objects/performLogin');
let shared = ({loginData, performLogin});
let page = ({pupilLogin});
const firstLogin = require('../shared_steps/firstLogin.js');
const Login = require('../shared-objects/loginData');
let teacherLogin = require('../page-objects/teacherLogin');


Given(/^teacher has come to schul-cloud home page$/, function () {
    return helpers.loadPage(shared.loginData.url, 10);
});
Given(/^teacher has logged in$/, function () {
    return teacherLogin.performLogin(Login.defaultTeacherUsername, Login.defaultTeacherpassword);
});
Given(/^teacher has created a user without submitting the age$/, function () {
    let firstname = "New Student";
    let lastname = "Under 14";
    let email = "underfourteen@schul-cloud.org";
    return administration.createNewPupil(firstname, lastname, email)
});
Given(/^teacher has created a link$/, function () {
    return registration.generateLink();
});
// User is under 14
When(/^user navigates a link$/, function () {
    return registration.openTheLink();
});
When(/^user should choose that the user is under 16$/, function () {
    return registration.submitThatTheUserIsUnder16();
});
When(/^user should submit the birthday information$/, function () {
    let student_age = 13;
    return registration.parentsSetStudentsAge(student_age);
});
When(/^parents of the student should submit a consent$/, function () {
    return registration.parentsSetTheirData();
});
When(/^parents should submit a code from the email generated by the system$/, function () {
    return registration.parentsSetPin();
});
When(/^parents press login button$/, function () {
    return registration.parentsGoToLogin();
});
When(/^user can log in with the data which was set by the parents$/, function () {
    return helpers.loadPage(shared.loginData.url, 10);
});
