
@firstLoginWithoutAgeData
Feature: first login
Background: teacher has created a user without submiting age
Given teacher has come to schul-cloud home page
Given teacher has logged in 
Given teacher has created a user without submitting the age
Given teacher has created a link

Scenario: User is under 14 and user makes first login
When user navigates a link
Then user should choose that the user is under 16
Then user should submit the birthday information
Then parents of the student should submit a consent
Then parents should submit a code from the email generated by the system
Then parents press login button
Then user can log in with the data which was set by the parents

#Scenario:  User is 14 >= x >16 and user makes first login
#When user navigates a link generated by teacher
#Then user should choose that the User is under 16
#Then User should submit the birthday information
#Then parents of the Student should submit a consent
#Then parents should submit a code from the email generated by the system
#Then student set password and finish the registration process
#Then user can log in with the data which was set in previous steps

#Scenario: User is >=16 and makes first login
#When user navigates the genirated link
#Then user should choose that the user is over 16
#Then user should submit the birthday info
#Then the student should submit a consent
#Then the student should submit a code from the email generated by the system
#Then the student sets password and finishes the registration process
#Then the student can log in with the data 


